fix overflow panic when moving in the data
the panic
```
thread 'app::tests::navigate_the_data' panicked at 'attempt to add with overflow', src/navigation.rs:73:30
```